# Generated by Django 2.2.6 on 2019-12-03 17:41

from django.db import migrations, models
import django.db.models.deletion
import mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_total', models.FloatField(default=0.0)),
                ('passives_total', models.FloatField(default=0.0)),
                ('reported', models.BooleanField(default=False)),
                ('date_created', mixins.models.MyDateField(auto_now_add=True)),
                ('date_report', mixins.models.MyDateField(blank=True, null=True)),
                ('period', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OperativeAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=3)),
                ('start_saldo_credit', models.FloatField(default=0.0)),
                ('start_saldo_debit', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=0.2)),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_saldo_credit', models.FloatField(default=0.0)),
                ('turnover_credit', models.FloatField(default=0.0)),
                ('end_saldo_credit', models.FloatField(default=0.0)),
                ('start_saldo_debit', models.FloatField(default=0.0)),
                ('turnover_debit', models.FloatField(default=0.0)),
                ('end_saldo_debit', models.FloatField(default=0.0)),
                ('date_created', mixins.models.MyDateField(auto_now_add=True)),
                ('date_report', mixins.models.MyDateField(blank=True, null=True)),
                ('period', models.IntegerField(default=0)),
                ('reported', models.BooleanField(default=False)),
                ('dicts_of_accs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('credit_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('operative_day', mixins.models.MyDateField(auto_now_add=True)),
                ('ab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passives', to='general_accounting.AccountingBalance')),
                ('op_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passives', to='general_accounting.OperativeAccounts')),
                ('tb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passives', to='general_accounting.TrialBalance')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('credit_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('operative_day', mixins.models.MyDateField(auto_now_add=True)),
                ('ab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='general_accounting.AccountingBalance')),
                ('op_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='general_accounting.OperativeAccounts')),
                ('tb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='general_accounting.TrialBalance')),
            ],
        ),
    ]
